# We actually depend on this being the generic image
language: generic

git:
  depth: 10

# don't re-build for tags so that [publish binary] is not re-run
# https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^v[0-9]/

cache:
  directories:
  - ${HOME}/.ccache

notifications:
  email: false
  slack:
    secure: Gnrl9VgCtWnBpN1UgLmE5TLnYR91X/bQQ3OavskN9vMXrDO5l8Aqx78u7pcE42hBYjLh5NaKyhQkbyPa4o5A+HvG1rj/OJyVvDAZwzktKn+O3VbqvT5Pqq/1ohHxVNZz4M2Ho5ROGhd+u1UhrAkANPM4/Xvd0gFiPTuCngeoZnE=
    on_success: change
    on_failure: change

sudo: false

env:
  global:
   - CCACHE_TEMPDIR=/tmp/.ccache-temp
   - CCACHE_COMPRESS=1
   - CASHER_TIME_OUT=1000
   - CC="clang"
   - CXX="clang++"
   - secure: KitzGZjoDblX/3heajcvssGz0JnJ/k02dr2tu03ksUV+6MogC3RSQudqyKY57+f8VyZrcllN/UOlJ0Q/3iG38Oz8DljC+7RZxtkVmE1SFBoOezKCdhcvWM12G3uqPs7hhrRxuUgIh0C//YXEkulUrqa2H1Aj2xeen4E3FAqEoy0=
   - secure: WLGmxl6VTVWhXGm6X83GYNYzPNsvTD+9usJOKM5YBLAdG7cnOBQBNiCCUKc9OZMMZVUr3ec2/iigakH5Y8Yc+U6AlWKzlORyqWLuk4nFuoedu62x6ocQkTkuOc7mHiYhKd21xTGMYauaZRS6kugv4xkpGES2UjI2T8cjZ+LN2jU=

addons_default: &apt_packages
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    # note: libstdc++-5-dev is required by clang-3.8 for its headers (clang-3.8 is installed by mason on linux)
    packages: [ 'libstdc++-5-dev', 'apport', 'gdb' ]

script_default: &build_and_publish
    - ./scripts/build.sh
    - ./scripts/publish.sh

matrix:
  include:
    # Linux
    - os: linux
      env: NODE="4" TARGET=Release
      addons: *apt_packages
      script: *build_and_publish
    - os: linux
      env: NODE="4" TARGET=Debug NPM_FLAGS="--debug"
      addons: *apt_packages
      script: *build_and_publish
    - os: linux
      env: NODE="6" TARGET=Release
      addons: *apt_packages
      script: *build_and_publish
    - os: linux
      env: NODE="6" TARGET=Debug NPM_FLAGS="--debug"
      addons: *apt_packages
      script: *build_and_publish
    # OS X
    - os: osx
      # https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions
      osx_image: xcode8
      env: NODE="4" TARGET=Release
      script: *build_and_publish
    - os: osx
      osx_image: xcode8
      env: NODE="4" TARGET=Debug NPM_FLAGS="--debug"
      script: *build_and_publish
    - os: osx
      # https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions
      osx_image: xcode8
      env: NODE="6" TARGET=Release
      script: *build_and_publish
    - os: osx
      osx_image: xcode8
      env: NODE="6" TARGET=Debug NPM_FLAGS="--debug"
      script: *build_and_publish
    # Linux coverage build
    - os: linux
      env: NODE="4" TARGET=Debug COVERAGE=true NPM_FLAGS="--debug"
      addons: *apt_packages
      script:
        - ./scripts/build.sh
        - curl -S -f https://codecov.io/bash -o codecov
        - chmod +x codecov
        - ./codecov -x "llvm-cov gcov" -Z
